### ISSUE TITLE
Why does Test-xDSCResource require admin rights?

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xDSCResourceDesigner#53]
I'm doing some local testing of xSharePoint and the Test-xDSCResource module gets called as part of the test suite there - I'm seeing errors when I run it locally saying that it needs to have admin rights to run though. Now I can just run it as admin, but I'm wondering what the requirement for something that is just validating a schema is to have admin rights when running?

**Comment by BrianFarnhill** [comment]
Does anyone have any input on this? It's really quite troublesome to have to launch a separate admin window of powershell to run our tests and I'm struggling to understand what the requirement is for something that is validating the contents of a text file to need admin rights to do that.

**Comment by gaelcolas** [comment]
I know it's old, but I believe Local Admin is required because it uses MofComp (C:\WINDOWS\system32\wbem\mofcomp.exe) to validate the MOF.
In `Test-MockSchema` called in `Test-xDscSchemaInternal` by `Test-xDscResource`.
```PowerShell
$parseResult = &$mofcomp -N:root\microsoft\windows\DesiredStateConfiguration -class:forceupdate $newSchemaPath
```
So it's doing more than just validating content, it tries to compile the MOF, and I suspect that access to that WMI namespace is restricted to Admins.

Running the command as non-admin give me the below:
```
...
MOF file has been successfully parsed
Storing data in the repository...
An error occurred while opening the namespace for object 1 defined on lines 3 - 11:
Error Number: 0x80041003, Facility: WMI
Description: Access denied
Compiler returned error 0x80041003
```

**Comment by johlju** [comment]
Closing this as solved as per previous comment. Please reopen or comment if this was closed in error.
